services:
  dev-env:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        GIT_USER: ${GIT_USER}
        GIT_EMAIL: ${GIT_EMAIL}
        JAVA_VERSION: ${JAVA_VERSION}
        NODE_VERSION: ${NODE_VERSION}

    restart: always
    volumes:
      - ./:/root/app
      - ~/.ssh:/root/.ssh

    tty: true
    network_mode: host

  postgres:
    image: postgres:${POSTGRES_VERSION}

    restart: always
    ports:
      - 5432:5432
    volumes:
      - .data:/var/lib/postgres/data

    environment:
      POSTGRES_PASSWORD: dev
